name: Deploy to GitHub Pages

on:
  workflow_dispatch:
    
jobs:
  build:
    uses: ./.github/workflows/build.yml
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download build-output artifact
      uses: actions/download-artifact@v3
      with:
        name: build-output
        path: dist/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
